=== Hl4p3x/L2Scripts_H5_2268/dist/gameserver/data/spawn/spawn.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (spawn|territory)*>
<!ELEMENT spawn (territory|npc|point|rectangle|circle)*>
<!ATTLIST spawn
	name CDATA #IMPLIED
	group CDATA #IMPLIED
	respawn CDATA #IMPLIED
	count CDATA #IMPLIED
	respawn_random CDATA #IMPLIED
	respawn_pattern CDATA #IMPLIED
	period_of_day CDATA #IMPLIED>
<!ELEMENT territory (banned_territory|add)*>
<!ATTLIST territory
	name CDATA #IMPLIED>
<!ELEMENT banned_territory (add)*>
<!ELEMENT add (#PCDATA)>
<!ATTLIST add
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	zmin CDATA #REQUIRED
	zmax CDATA #REQUIRED>
<!ELEMENT npc (set)*>
<!ATTLIST npc
	id CDATA #REQUIRED
	max CDATA #IMPLIED
	ai_param CDATA #IMPLIED>
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT point (#PCDATA)>
<!ATTLIST point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #IMPLIED
	ai CDATA #IMPLIED
	superPoint CDATA #IMPLIED
	super_point CDATA #IMPLIED>
<!ELEMENT rectangle (#PCDATA)>
<!ATTLIST rectangle
	x1 CDATA #REQUIRED
	y1 CDATA #REQUIRED
	x2 CDATA #REQUIRED
	y2 CDATA #REQUIRED
	zmin CDATA #REQUIRED
	zmax CDATA #REQUIRED>
<!ELEMENT circle (#PCDATA)>
<!ATTLIST circle
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	zmin CDATA #REQUIRED
	zmax CDATA #REQUIRED
	radius CDATA #REQUIRED>

=== Hl4p3x/L2Scripts_H5_2268/dist/gameserver/data/spawn/instances/[111] Sanctum of the Dawn.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">
<!--AUTHOR: Bonux-->
<list>
	<spawn group="sanctum_of_the_dawn" count="1" respawn="0">
		<point x="-75988" y="213411" z="-7124" h="0"/>
		<npc id="32579"/><!--Darkness of Dawn-->
	</spawn>
	<spawn group="sanctum_of_the_dawn" count="1" respawn="0">
		<point x="-75695" y="213537" z="-7128" h="0"/>
		<npc id="32578"><!--Identity Confirm Device-->
			<set name="device_id" value="1"/>
		</npc>
	</spawn>
	<spawn group="sanctum_of_the_dawn" count="1" respawn="0">
		<point x="-78289" y="205749" z="-7884" h="0"/>
		<npc id="32578"><!--Identity Confirm Device-->
			<set name="device_id" value="2"/>
		</npc>
	</spawn>
	<spawn group="sanctum_of_the_dawn" count="1" respawn="0">
		<point x="-80152" y="205740" z="-7904" h="0"/>
		<npc id="32577"/><!--Password Entry Device-->
	</spawn>
	<spawn group="sanctum_of_the_dawn" count="1" respawn="0">
		<point x="-81384" y="205560" z="-8012" h="65342"/>
		<npc id="32580"/><!---->
	</spawn>
</list>

=== Hl4p3x/L2Scripts_H5_2268/dist/gameserver/data/spawn/13_25.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">

<list>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-204849" y="242148" z="1781" h="0" />
		<npc id="32518" /><!--Vortex Gate -->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-223211" y="247803" z="1781" h="0" />
		<npc id="32519" /><!--Vortex Gate -->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-223331" y="233909" z="4166" h="0" />
		<npc id="18690" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-224189" y="233518" z="4569" h="0" />
		<npc id="18690" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-224618" y="237037" z="4867" h="0" />
		<npc id="18690" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-226334" y="232736" z="5046" h="0" />
		<npc id="18690" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-221615" y="233518" z="4360" h="0" />
		<npc id="18690" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-221615" y="232736" z="4569" h="0" />
		<npc id="18690" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-220757" y="233127" z="4864" h="0" />
		<npc id="18691" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-222044" y="233127" z="4246" h="0" />
		<npc id="18691" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-222473" y="237037" z="5276" h="0" />
		<npc id="18691" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-224189" y="233909" z="4879" h="0" />
		<npc id="18691" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-226763" y="233909" z="5393" h="0" />
		<npc id="18691" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-226334" y="234300" z="5411" h="0" />
		<npc id="18691" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-227192" y="233909" z="5229" h="0" />
		<npc id="18691" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-223760" y="237037" z="4733" h="0" />
		<npc id="18692" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-225476" y="238601" z="4107" h="0" />
		<npc id="18692" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-224618" y="232345" z="5341" h="0" />
		<npc id="18692" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-221186" y="232345" z="5436" h="0" />
		<npc id="18692" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-221186" y="235082" z="3960" h="0" />
		<npc id="18692" /><!--Green Star Stone-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<point x="-222473" y="235473" z="4018" h="0" />
		<npc id="18692" /><!--Green Star Stone-->
	</spawn>
</list>
