=== Hl4p3x/L2Scripts_H5_2268/dist/gameserver/data/fake_players/fake_player.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT fake_player_ai (on_character_create|farm|action)*>
<!ATTLIST fake_player_ai
		race CDATA #REQUIRED
		type CDATA #REQUIRED>

	<!ELEMENT on_character_create (wait|move_to_npc|speak_with_npc|random_action|ordinary_actions|repeat_actions|move_to_point|use_item|use_community|add_item|teleport_to_point|teleport_to_closest_town|farm|action)*>

		<!ELEMENT random_action (wait|move_to_npc|speak_with_npc|random_action|ordinary_actions|repeat_actions|move_to_point|use_item|use_community|add_item|teleport_to_point|teleport_to_closest_town|farm|action)*>
		<!ATTLIST random_action
				chance CDATA #IMPLIED>

		<!ELEMENT ordinary_actions (wait|move_to_npc|speak_with_npc|random_action|ordinary_actions|repeat_actions|move_to_point|use_item|use_community|add_item|teleport_to_point|teleport_to_closest_town|farm|action)*>
		<!ATTLIST ordinary_actions
				chance CDATA #IMPLIED>

		<!ELEMENT repeat_actions (wait|move_to_npc|speak_with_npc|random_action|ordinary_actions|repeat_actions|move_to_point|use_item|use_community|add_item|teleport_to_point|teleport_to_closest_town|farm|action)*>
		<!ATTLIST repeat_actions
				count CDATA #IMPLIED
				min_count CDATA #IMPLIED
				max_count CDATA #IMPLIED
				chance CDATA #IMPLIED>

		<!ELEMENT wait (#PCDATA)>
		<!ATTLIST wait
				delay CDATA #IMPLIED
				min_delay CDATA #IMPLIED
				max_delay CDATA #IMPLIED
				chance CDATA #IMPLIED>

		<!ELEMENT move_to_npc (#PCDATA)>
		<!ATTLIST move_to_npc
				id CDATA #REQUIRED
				chance CDATA #IMPLIED>

		<!ELEMENT speak_with_npc (#PCDATA)>
		<!ATTLIST speak_with_npc
				id CDATA #REQUIRED
				bypass CDATA #IMPLIED
				chance CDATA #IMPLIED>

		<!ELEMENT move_to_point (#PCDATA)>
		<!ATTLIST move_to_point
				x CDATA #REQUIRED
				y CDATA #REQUIRED
				z CDATA #REQUIRED
				range CDATA #IMPLIED
				min_range CDATA #IMPLIED
				max_range CDATA #IMPLIED
				chance CDATA #IMPLIED>

		<!ELEMENT use_item (#PCDATA)>
		<!ATTLIST use_item
				id CDATA #REQUIRED
				chance CDATA #IMPLIED>

		<!ELEMENT use_community (#PCDATA)>
		<!ATTLIST use_community
				bypass CDATA #REQUIRED>

		<!ELEMENT add_item (#PCDATA)>
		<!ATTLIST add_item
				id CDATA #REQUIRED
				count CDATA #IMPLIED
				min_count CDATA #IMPLIED
				max_count CDATA #IMPLIED
				chance CDATA #IMPLIED>

		<!ELEMENT teleport_to_point (#PCDATA)>
		<!ATTLIST teleport_to_point
				x CDATA #REQUIRED
				y CDATA #REQUIRED
				z CDATA #REQUIRED
				chance CDATA #IMPLIED>

		<!ELEMENT teleport_to_closest_town (#PCDATA)>
		<!ATTLIST teleport_to_closest_town
				chance CDATA #IMPLIED>

<!ELEMENT farm (zones|farm_monsters|ignored_monsters|on_obtain_max_level|go_to_town|action)*>
<!ATTLIST farm
		name CDATA #IMPLIED
		min_level CDATA #IMPLIED
		max_level CDATA #IMPLIED
		classes CDATA #IMPLIED
		types CDATA #IMPLIED
		races CDATA #IMPLIED>

	<!ELEMENT zones (zone|spawn_points)*>

		<!ELEMENT zone (polygon|circle|rectangle|banned_polygon|restart_point|PKrestart_point)*>
		<!ATTLIST zone
			name CDATA #IMPLIED>

			<!ELEMENT polygon (coords)*>

			<!ELEMENT circle (coords)*>
			<!ATTLIST circle
				loc CDATA #IMPLIED>

			<!ELEMENT rectangle (coords)*>

			<!ELEMENT banned_polygon (coords)*>

				<!ELEMENT coords (#PCDATA)>
				<!ATTLIST coords
					loc CDATA #REQUIRED
					chance CDATA #IMPLIED>

		<!ELEMENT spawn_points (coords)*>

	<!ELEMENT farm_monsters (npc)*>

	<!ELEMENT ignored_monsters (npc)*>

			<!ELEMENT npc (#PCDATA)>
			<!ATTLIST npc
				id CDATA #REQUIRED>

	<!ELEMENT on_obtain_max_level (wait|move_to_npc|speak_with_npc|random_action|ordinary_actions|repeat_actions|move_to_point|use_item|use_community|add_item|teleport_to_point|teleport_to_closest_town|farm|action)*>

	<!ELEMENT go_to_town (wait|move_to_npc|speak_with_npc|random_action|ordinary_actions|repeat_actions|move_to_point|use_item|use_community|add_item|teleport_to_point|teleport_to_closest_town|farm|action)*>
	<!ATTLIST go_to_town
			farm_time CDATA #IMPLIED
			min_farm_time CDATA #IMPLIED
			max_farm_time CDATA #IMPLIED
			chance CDATA #IMPLIED>

<!ELEMENT town (zones|actions|action)*>
<!ATTLIST town
		name CDATA #REQUIRED>

	<!ELEMENT actions (wait|move_to_npc|speak_with_npc|random_action|ordinary_actions|repeat_actions|move_to_point|use_item|use_community|add_item|teleport_to_point|teleport_to_closest_town|farm|action)*>

<!ELEMENT action (wait|move_to_npc|speak_with_npc|random_action|ordinary_actions|repeat_actions|move_to_point|use_item|use_community|add_item|teleport_to_point|teleport_to_closest_town|farm|action)*>
<!ATTLIST action
		id CDATA #REQUIRED
		chance CDATA #IMPLIED>

=== Hl4p3x/L2Scripts_H5_2268/dist/gameserver/data/fake_players/town/[12] town_of_oren.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE town SYSTEM "fake_player.dtd">
<!--AUTHOR: Bonux-->
<town name="Town of Oren">
	<zones>
		<zone name="[oren_town_peace1]"/>
	</zones>
	<actions>
		<wait min_delay="1000" max_delay="3000"/>
		<random_action>
			<ordinary_actions>
				<move_to_point x="82344" y="53368" z="-1488" min_range="50" max_range="100"/>
				<move_to_point x="80824" y="53608" z="-1552" min_range="50" max_range="100"/>
				<move_to_point x="80472" y="53640" z="-1552" min_range="50" max_range="100"/>
				<move_to_point x="79864" y="53160" z="-1552" min_range="50" max_range="100"/>
				<move_to_point x="79640" y="53304" z="-1552" min_range="50" max_range="100"/>
				<move_to_point x="79624" y="53576" z="-1544" min_range="50" max_range="100"/>
				<move_to_point x="79320" y="53624" z="-1544" min_range="50" max_range="100"/>
				<random_action>
					<ordinary_actions>
						<move_to_npc id="30178"/>
						<speak_with_npc id="30178"/>
					</ordinary_actions>
					<ordinary_actions>
						<move_to_npc id="30179"/>
						<speak_with_npc id="30179"/>
					</ordinary_actions>
				</random_action>
				<wait min_delay="2000" max_delay="5000"/>
				<move_to_point x="79320" y="53624" z="-1544" min_range="50" max_range="100"/>
				<move_to_point x="79624" y="53576" z="-1544" min_range="50" max_range="100"/>
				<move_to_point x="79640" y="53304" z="-1552" min_range="50" max_range="100"/>
				<move_to_point x="79864" y="53160" z="-1552" min_range="50" max_range="100"/>
				<move_to_point x="80472" y="53640" z="-1552" min_range="50" max_range="100"/>
				<move_to_point x="80824" y="53608" z="-1552" min_range="50" max_range="100"/>
				<move_to_point x="82344" y="53368" z="-1488" min_range="50" max_range="100"/>
			</ordinary_actions>
			<ordinary_actions>
				<move_to_point x="82520" y="53448" z="-1488" min_range="50" max_range="100"/>
				<move_to_point x="82312" y="54664" z="-1520" min_range="50" max_range="100"/>
				<move_to_point x="82040" y="55448" z="-1520" min_range="50" max_range="100"/>
				<move_to_point x="81480" y="55688" z="-1520" min_range="50" max_range="100"/>
				<move_to_point x="80728" y="55256" z="-1536" min_range="50" max_range="100"/>
				<move_to_point x="80296" y="54952" z="-1552" min_range="50" max_range="100"/>
				<move_to_point x="79976" y="54888" z="-1544" min_range="50" max_range="100"/>
				<move_to_point x="79592" y="54920" z="-1544" min_range="50" max_range="100"/>
				<random_action>
					<ordinary_actions>
						<move_to_npc id="30180"/>
						<speak_with_npc id="30180"/>
					</ordinary_actions>
					<ordinary_actions>
						<move_to_npc id="30181"/>
						<speak_with_npc id="30181"/>
					</ordinary_actions>
				</random_action>
				<wait min_delay="2000" max_delay="5000"/>
				<move_to_point x="79592" y="54920" z="-1544" min_range="50" max_range="100"/>
				<move_to_point x="79976" y="54888" z="-1544" min_range="50" max_range="100"/>
				<move_to_point x="80296" y="54952" z="-1552" min_range="50" max_range="100"/>
				<move_to_point x="80728" y="55256" z="-1536" min_range="50" max_range="100"/>
				<move_to_point x="81480" y="55688" z="-1520" min_range="50" max_range="100"/>
				<move_to_point x="82040" y="55448" z="-1520" min_range="50" max_range="100"/>
				<move_to_point x="82312" y="54664" z="-1520" min_range="50" max_range="100"/>
				<move_to_point x="82520" y="53448" z="-1488" min_range="50" max_range="100"/>
			</ordinary_actions>
			<ordinary_actions>
				<move_to_point x="82392" y="53416" z="-1488" min_range="50" max_range="100"/>
				<move_to_point x="81032" y="53576" z="-1552" min_range="50" max_range="100"/>
				<move_to_point x="81032" y="54696" z="-1520" min_range="50" max_range="100"/>
				<move_to_point x="81336" y="54728" z="-1504" min_range="50" max_range="100"/>
				<move_to_point x="81352" y="54888" z="-1504" min_range="50" max_range="100"/>
				<random_action>
					<ordinary_actions>
						<move_to_npc id="30182"/>
						<speak_with_npc id="30182"/>
					</ordinary_actions>
					<ordinary_actions>
						<move_to_npc id="30183"/>
						<speak_with_npc id="30183"/>
					</ordinary_actions>
				</random_action>
				<wait min_delay="2000" max_delay="5000"/>
				<move_to_point x="81352" y="54888" z="-1504" min_range="50" max_range="100"/>
				<move_to_point x="81336" y="54728" z="-1504" min_range="50" max_range="100"/>
				<move_to_point x="81032" y="54696" z="-1520" min_range="50" max_range="100"/>
				<move_to_point x="81032" y="53576" z="-1552" min_range="50" max_range="100"/>
				<move_to_point x="82392" y="53416" z="-1488" min_range="50" max_range="100"/>
			</ordinary_actions>
		</random_action>
		<ordinary_actions chance="30">
			<move_to_point x="82472" y="53352" z="-1488" min_range="50" max_range="100"/>
			<move_to_point x="82920" y="53208" z="-1488" min_range="50" max_range="100"/>
			<move_to_npc id="30177"/>
			<speak_with_npc id="30177"/>
		</ordinary_actions>
		<wait min_delay="2000" max_delay="5000"/>
		<farm/>
	</actions>
</town>

=== Hl4p3x/L2Scripts_H5_2268/dist/gameserver/data/fake_players/farm/race/orc/[1] paagrio_temple.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE farm SYSTEM "fake_player.dtd">
<!--AUTHOR: Bonux-->
<farm name="Paagrio Temple" min_level="1" max_level="3" races="ORC">
	<zones>
		<zone>
			<polygon>
				<coords loc="-57432 -112248 -800 -500"/>
				<coords loc="-57560 -113144 -800 -500"/>
				<coords loc="-58440 -113272 -800 -500"/>
				<coords loc="-58456 -113896 -800 -500"/>
				<coords loc="-57560 -114072 -800 -500"/>
				<coords loc="-57432 -114936 -800 -500"/>
				<coords loc="-56776 -114968 -800 -500"/>
				<coords loc="-56664 -114056 -800 -500"/>
				<coords loc="-55608 -113928 -800 -500"/>
				<coords loc="-55544 -113288 -800 -500"/>
				<coords loc="-56632 -113144 -800 -500"/>
				<coords loc="-56760 -112248 -800 -500"/>
			</polygon>
		</zone>
		<spawn_points>
			<coords loc="-56733 -113459 -690 0"/>
			<coords loc="-56686 -113470 -690 0"/>
			<coords loc="-56728 -113610 -690 0"/>
			<coords loc="-56693 -113610 -690 0"/>
			<coords loc="-56743 -113757 -690 0"/>
			<coords loc="-56682 -113730 -690 0"/>
		</spawn_points>
	</zones>
	<farm_monsters>
		<npc id="18342"/>
	</farm_monsters>
	<on_obtain_max_level>
		<wait min_delay="1000" max_delay="3000"/>
		<move_to_point x="-56136" y="-113592" z="-672" min_range="50" max_range="150"/>
		<move_to_point x="-55352" y="-113608" z="-672" min_range="0" max_range="50"/>
		<move_to_point x="-54568" y="-113624" z="-480" min_range="0" max_range="50"/>
		<move_to_point x="-53688" y="-113624" z="-192" min_range="0" max_range="50"/>
		<move_to_point x="-53144" y="-113624" z="-80" min_range="0" max_range="50"/>
		<move_to_point x="-52392" y="-113624" z="-80" min_range="0" max_range="50"/>
		<move_to_point x="-51464" y="-113608" z="-160" min_range="0" max_range="50"/>
		<move_to_point x="-50984" y="-113608" z="-176" min_range="50" max_range="150"/>
		<random_action>
			<ordinary_actions>
				<random_action>
					<ordinary_actions>
						<move_to_point x="-50952" y="-112632" z="-192" min_range="50" max_range="150"/>
					</ordinary_actions>
					<ordinary_actions>
						<move_to_point x="-50696" y="-114680" z="-176" min_range="50" max_range="150"/>
					</ordinary_actions>
				</random_action>
				<farm/>
			</ordinary_actions>
			<ordinary_actions>
				<move_to_point x="-50184" y="-113608" z="-176" min_range="0" max_range="50"/>
				<move_to_point x="-49048" y="-113608" z="-240" min_range="0" max_range="50"/>
				<move_to_point x="-47864" y="-113608" z="-224" min_range="0" max_range="50"/>
				<move_to_point x="-46920" y="-113608" z="-200" min_range="0" max_range="0"/>
				<move_to_point x="-46376" y="-113608" z="-200" min_range="0" max_range="50"/>
				<move_to_point x="-45512" y="-113608" z="-240" min_range="0" max_range="50"/>
				<move_to_point x="-45192" y="-113592" z="-224" min_range="0" max_range="50"/>
			</ordinary_actions>
		</random_action>
	</on_obtain_max_level>
</farm>

=== Hl4p3x/L2Scripts_H5_2268/dist/gameserver/data/fake_players/farm/race/darkelf/[6] lvl 14-20.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE farm SYSTEM "fake_player.dtd">
<!--AUTHOR: Bonux-->
<farm name="Dark Elf (Lvl 14-20)" min_level="14" max_level="20" races="DARKELF">
	<zones>
		<zone>
			<polygon>
				<coords loc="-14936 29192 -3798 -3498"/>
				<coords loc="-6398 37136 -3830 -3530"/>
				<coords loc="-10597 48147 -3926 -3626"/>
				<coords loc="-21352 55320 -3814 -3514"/>
				<coords loc="-28404 48913 -3830 -3530"/>
				<coords loc="-23480 36616 -3126 -2826"/>
			</polygon>
		</zone>
		<spawn_points>
			<coords loc="-22968 37304 -2832"/>
			<coords loc="-20360 39576 -3280"/>
			<coords loc="-21096 41944 -3552"/>
		</spawn_points>
	</zones>
	<on_obtain_max_level>
		<action id="1"/>
	</on_obtain_max_level>
	<go_to_town min_farm_time="1800" max_farm_time="3600">
		<action id="1"/>
	</go_to_town>
	<action id="1">
		<wait min_delay="1000" max_delay="3000"/>
		<random_action>
			<ordinary_actions>
				<move_to_point x="-24264" y="37640" z="-3008" min_range="50" max_range="150"/>
				<move_to_point x="-23528" y="36824" z="-2976" min_range="50" max_range="150"/>
				<move_to_point x="-22312" y="35544" z="-3024" min_range="50" max_range="150"/>
				<move_to_point x="-21208" y="34168" z="-3104" min_range="0" max_range="50"/>
				<move_to_point x="-18920" y="32680" z="-3632" min_range="50" max_range="150"/>
				<move_to_point x="-17736" y="31336" z="-3632" min_range="0" max_range="50"/>
				<move_to_point x="-16008" y="30312" z="-3616" min_range="0" max_range="50"/>
				<move_to_point x="-14952" y="29096" z="-3648" min_range="0" max_range="50"/>
				<move_to_point x="-13736" y="26232" z="-3712" min_range="0" max_range="50"/>
				<move_to_point x="-12872" y="25000" z="-3712" min_range="0" max_range="50"/>
				<move_to_point x="-11240" y="23752" z="-3728" min_range="50" max_range="150"/>
				<move_to_point x="-9528" y="22600" z="-3712" min_range="0" max_range="50"/>
				<move_to_point x="-8232" y="22136" z="-3712" min_range="0" max_range="50"/>
				<move_to_point x="-6904" y="21960" z="-3664" min_range="0" max_range="50"/>
				<move_to_point x="-5576" y="21992" z="-3536" min_range="0" max_range="50"/>
				<move_to_point x="-3768" y="21912" z="-3456" min_range="0" max_range="50"/>
				<move_to_point x="-2632" y="21144" z="-3472" min_range="0" max_range="50"/>
				<move_to_point x="-1128" y="20136" z="-3360" min_range="0" max_range="50"/>
				<move_to_point x="-184" y="19976" z="-3344" min_range="50" max_range="150"/>
				<move_to_point x="1224" y="20776" z="-3456" min_range="0" max_range="50"/>
				<move_to_point x="3320" y="20760" z="-3696" min_range="0" max_range="50"/>
				<move_to_point x="4536" y="20328" z="-3712" min_range="0" max_range="50"/>
				<move_to_point x="5960" y="19912" z="-3728" min_range="0" max_range="50"/>
				<move_to_point x="6760" y="19624" z="-3712" min_range="0" max_range="0"/>
				<move_to_point x="6920" y="19208" z="-3784" min_range="0" max_range="0"/>
				<move_to_point x="6728" y="18808" z="-3936" min_range="0" max_range="0"/>
				<move_to_point x="6104" y="18536" z="-4112" min_range="0" max_range="0"/>
				<move_to_point x="6104" y="17992" z="-4240" min_range="0" max_range="0"/>
				<move_to_point x="6552" y="17832" z="-4320" min_range="0" max_range="0"/>
				<move_to_point x="7224" y="17784" z="-4384" min_range="0" max_range="50"/>
				<move_to_point x="8088" y="17608" z="-4456" min_range="50" max_range="150"/>
				<move_to_point x="9128" y="17368" z="-4584" min_range="50" max_range="150"/>
				<move_to_point x="9864" y="17208" z="-4584" min_range="50" max_range="150"/>
				<move_to_point x="10440" y="17064" z="-4584" min_range="50" max_range="150"/>
				<move_to_point x="11240" y="16872" z="-4656" min_range="0" max_range="50"/>
			</ordinary_actions>
			<use_item id="736"/>
		</random_action>
	</action>
</farm>

=== Hl4p3x/L2Scripts_H5_2268/dist/gameserver/data/fake_players/farm/[6] execution_grounds.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE farm SYSTEM "fake_player.dtd">
<!--AUTHOR: Bonux-->
<farm name="Execution Ground" min_level="32" max_level="38">
	<zones>
		<zone>
			<polygon>
				<coords loc="46008 144392 -4000 -3000"/>
				<coords loc="46872 143480 -4000 -3000"/>
				<coords loc="49448 143048 -4000 -3000"/>
				<coords loc="50200 144552 -4000 -3000"/>
				<coords loc="50664 145464 -4000 -3000"/>
				<coords loc="51048 146008 -4000 -3000"/>
				<coords loc="51416 146392 -4000 -3000"/>
				<coords loc="50664 147992 -4000 -3000"/>
				<coords loc="49528 148888 -4000 -3000"/>
				<coords loc="48472 149752 -4000 -3000"/>
				<coords loc="47080 149912 -4000 -3000"/>
				<coords loc="46328 149480 -4000 -3000"/>
				<coords loc="45816 148904 -4000 -3000"/>
				<coords loc="44504 149128 -4000 -3000"/>
				<coords loc="42776 147976 -4000 -3000"/>
				<coords loc="43208 147080 -4000 -3000"/>
				<coords loc="42824 145800 -4000 -3000"/>
				<coords loc="45016 145592 -4000 -3000"/>
				<coords loc="45512 144808 -4000 -3000"/>
			</polygon>
		</zone>
		<spawn_points>
			<coords loc="47848 146344 -3576"/>
		</spawn_points>
	</zones>
	<on_obtain_max_level>
		<action id="1"/>
	</on_obtain_max_level>
	<go_to_town min_farm_time="1800" max_farm_time="3600">
		<action id="1"/>
	</go_to_town>
	<action id="1">
		<wait min_delay="1000" max_delay="3000"/>
		<use_item id="736"/>
	</action>
</farm>

=== Hl4p3x/L2Scripts_H5_2268/dist/gameserver/data/fake_players/ai/[1] human_mystic.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE fake_player_ai SYSTEM "fake_player.dtd">
<!--AUTHOR: Bonux-->
<fake_player_ai race="HUMAN" type="MYSTIC">
	<on_character_create>	<!--Создается персонаж-->
		<wait min_delay="3000" max_delay="9000"/>
		<move_to_npc id="30019"/>
		<speak_with_npc id="30019"/>
		<wait min_delay="1000" max_delay="3000"/>
		<wait min_delay="500" max_delay="1500"/>
		<farm/>
	</on_character_create>
	<farm name="Einhasad Magic School" min_level="1" max_level="3">
		<zones>
			<zone>
				<polygon>
					<coords loc="-91112 248264 -3650 -3450"/>
					<coords loc="-90328 248904 -3650 -3450"/>
					<coords loc="-89912 248344 -3650 -3450"/>
					<coords loc="-90840 247832 -3650 -3450"/>
					<coords loc="-91048 247848 -3650 -3450"/>
					<coords loc="-91208 248072 -3650 -3450"/>
				</polygon>
			</zone>
			<spawn_points>
				<coords loc="-90875 248162 -3570 0"/>
				<coords loc="-90954 248118 -3570 0"/>
				<coords loc="-90918 248070 -3570 0"/>
				<coords loc="-90890 248027 -3570 0"/>
			</spawn_points>
		</zones>
		<farm_monsters>
			<npc id="18342"/>
		</farm_monsters>
		<on_obtain_max_level>
			<wait min_delay="1000" max_delay="3000"/>
			<action id="1"/>
			<action id="2" chance="60"/>
			<farm/>
		</on_obtain_max_level>
	</farm>
	<farm name="Human Mystic Farm 1" min_level="2" max_level="4">
		<zones>
			<zone>
				<polygon>
					<coords loc="-87896 250936 -3782 -3482"/>
					<coords loc="-88104 251832 -3798 -3498"/>
					<coords loc="-87784 253880 -3846 -3546"/>
					<coords loc="-87384 255816 -3894 -3594"/>
					<coords loc="-86344 256552 -3878 -3578"/>
					<coords loc="-84312 255096 -3878 -3578"/>
					<coords loc="-82984 253480 -3894 -3594"/>
					<coords loc="-84152 251848 -3814 -3514"/>
					<coords loc="-85080 250312 -3606 -3306"/>
					<coords loc="-86392 250248 -3638 -3338"/>
				</polygon>
			</zone>
			<spawn_points>
				<coords loc="-86600 250904 -3600"/>
			</spawn_points>
		</zones>
		<on_obtain_max_level>
			<wait min_delay="1000" max_delay="3000"/>
			<action id="2"/>
			<action id="3"/>
		</on_obtain_max_level>
	</farm>
	<farm name="Human Mystic Farm 2" min_level="2" max_level="4">
		<zones>
			<zone>
				<polygon>
					<coords loc="-79592 248088 -3850 -3450"/>
					<coords loc="-80824 243640 -3850 -3450"/>
					<coords loc="-84120 246584 -3850 -3450"/>
					<coords loc="-80952 249576 -3850 -3450"/>
				</polygon>
			</zone>
			<spawn_points>
				<coords loc="-81064 247160 -3648"/>
			</spawn_points>
		</zones>
		<on_obtain_max_level>
			<wait min_delay="1000" max_delay="3000"/>
			<action id="3"/>
		</on_obtain_max_level>
	</farm>
	<action id="1">	<!--Выходим из Магической Школы-->
		<move_to_point x="-90296" y="248504" z="-3568" min_range="0" max_range="50"/>
		<move_to_point x="-89608" y="248968" z="-3568" min_range="50" max_range="150"/>
		<random_action>
			<ordinary_actions>
				<move_to_point x="-89080" y="248760" z="-3568" min_range="50" max_range="150"/>
				<move_to_point x="-88264" y="248936" z="-3568" min_range="50" max_range="150"/>
				<move_to_point x="-88200" y="249512" z="-3584" min_range="50" max_range="150"/>
			</ordinary_actions>
			<ordinary_actions>
				<move_to_point x="-89624" y="249464" z="-3568" min_range="50" max_range="150"/>
				<move_to_point x="-89336" y="250200" z="-3568" min_range="0" max_range="50"/>
				<move_to_point x="-88840" y="250136" z="-3568" min_range="50" max_range="150"/>
			</ordinary_actions>
		</random_action>
		<move_to_point x="-88008" y="250072" z="-3600" min_range="0" max_range="50"/>
		<move_to_point x="-87704" y="250216" z="-3616" min_range="50" max_range="150"/>
		<move_to_point x="-87000" y="250840" z="-3616" min_range="50" max_range="150"/>
		<move_to_point x="-86376" y="251608" z="-3600" min_range="50" max_range="150"/>
	</action>
	<action id="2">	<!--Идем под южную часть деревни-->
		<move_to_point x="-86360" y="250824" z="-3584" min_range="50" max_range="150"/>
		<move_to_point x="-85352" y="250600" z="-3456" min_range="50" max_range="150"/>
		<move_to_point x="-84440" y="250120" z="-3440" min_range="50" max_range="150"/>
		<move_to_point x="-83224" y="249176" z="-3576" min_range="0" max_range="50"/>
		<move_to_point x="-81848" y="248200" z="-3696" min_range="50" max_range="150"/>
		<move_to_point x="-81496" y="246936" z="-3664" min_range="50" max_range="150"/>
	</action>
	<action id="3">	<!--Идем в дервеню от южной части деревни-->
		<move_to_point x="-81144" y="246792" z="-3664" min_range="50" max_range="150"/>
		<move_to_point x="-81560" y="246200" z="-3696" min_range="50" max_range="150"/>
		<move_to_point x="-82200" y="245256" z="-3712" min_range="50" max_range="150"/>
		<move_to_point x="-82872" y="244504" z="-3728" min_range="50" max_range="150"/>
		<move_to_point x="-83336" y="244056" z="-3728" min_range="50" max_range="150"/>
		<move_to_point x="-83944" y="243384" z="-3728" min_range="0" max_range="50"/>
	</action>
</fake_player_ai>

=== Hl4p3x/L2Scripts_H5_2268/dist/gameserver/data/fake_players/ai/[8] dwarven.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE fake_player_ai SYSTEM "fake_player.dtd">
<!--AUTHOR: Bonux-->
<fake_player_ai race="DWARF" type="FIGHTER">
	<on_character_create>	<!--Создается персонаж-->
		<wait min_delay="3000" max_delay="9000"/>
		<move_to_npc id="30530"/>
		<speak_with_npc id="30530"/>
		<wait min_delay="1000" max_delay="3000"/>
		<wait min_delay="500" max_delay="1500"/>
		<farm/>
	</on_character_create>
	<farm name="Rebirth Mine" min_level="1" max_level="3">
		<zones>
			<zone>
				<polygon>
					<coords loc="107928 -176168 -600 -300"/>
					<coords loc="106600 -173480 -600 -300"/>
					<coords loc="108984 -172472 -600 -300"/>
					<coords loc="110136 -174200 -600 -300"/>
					<coords loc="109000 -175752 -600 -300"/>
				</polygon>
			</zone>
			<spawn_points>
				<coords loc="108644 -173947 -400 0"/>
				<coords loc="108678 -174002 -400 0"/>
				<coords loc="108505 -173964 -400 0"/>
				<coords loc="108512 -174026 -400 0"/>
				<coords loc="108549 -174075 -400 0"/>
				<coords loc="108576 -174122 -400 0"/>
			</spawn_points>
		</zones>
		<farm_monsters>
			<npc id="18342"/>
		</farm_monsters>
		<on_obtain_max_level>
			<wait min_delay="1000" max_delay="3000"/>
			<move_to_point x="109256" y="-173752" z="-544" min_range="50" max_range="150"/>
			<move_to_point x="109688" y="-173720" z="-544" min_range="50" max_range="150"/>
			<move_to_point x="110456" y="-173704" z="-544" min_range="0" max_range="50"/>
			<move_to_point x="111480" y="-173544" z="-608" min_range="0" max_range="50"/>
			<move_to_point x="112568" y="-173672" z="-608" min_range="0" max_range="50"/>
			<move_to_point x="113240" y="-174328" z="-608" min_range="50" max_range="150"/>
			<move_to_point x="113432" y="-175112" z="-608" min_range="0" max_range="50"/>
			<move_to_point x="113656" y="-175768" z="-672" min_range="0" max_range="50"/>
			<move_to_point x="114120" y="-176280" z="-736" min_range="0" max_range="50"/>
			<move_to_point x="114664" y="-176424" z="-752" min_range="0" max_range="50"/>
			<move_to_point x="115048" y="-176664" z="-784" min_range="0" max_range="50"/>
			<move_to_point x="115272" y="-177416" z="-912" min_range="50" max_range="150"/>
			<move_to_point x="115416" y="-178296" z="-928" min_range="50" max_range="150"/>
		</on_obtain_max_level>
	</farm>
</fake_player_ai>
